// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


const ARGS_MAP = { 'common':'{"set_homeserver_url":[]}' }
export type Router = { 'common': { set_homeserver_url: () => Promise<void> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
