#!/bin/sh
# Commits all the edited files in tchap-infra into a branch and opens a PR.
set -e

TCHAP_INFRA_DIR="$1"
GITHUB_BRANCH="$2"
if [[ -z "$TCHAP_INFRA_DIR" ]]; then
    echo "Must provide TCHAP_INFRA_DIR" 1>&2
    exit 1
fi
if [[ -z "$GITHUB_BRANCH" ]]; then
    echo "Must provide BRANCH_NAME" 1>&2
    exit 1
fi

cd $TCHAP_INFRA_DIR
git checkout -B $GITHUB_BRANCH
git add .
git commit -m "Deployment of tchap-web"
#git push --set-upstream origin <branchname>
#open PR (needs gh cli) with description saying it's autogenerated.
