#Build the application
name: Build without E2E tests
on:
    pull_request: {}
    push:
        branches: [master]
    workflow_dispatch: # for running action manually

env:
    # These must be set for fetchdep.sh to get the right branch
    REPOSITORY: ${{ github.repository }}
    PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest

        # Only run on draft PRs. On ready_for_review PRs, we already have the Cypress job which runs the build
        if: github.event.pull_request.draft == true

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  cache: "pnpm"
                  node-version-file: package.json

            - name: Install Dependencies
              run: "pnpm install"

            - name: "Copy the config file at the right place"
              working-directory: apps/web
              run: "cp config.dev.json config.json" # todo we could make the choice of backend configurable.

            - name: Build
              working-directory: apps/web
              run: "pnpm build"

            - name: Upload build in artifact
              uses: actions/upload-artifact@v4
              with:
                  name: devbuild # because we used the dev config file
                  path: apps/web/webapp
                  # We'll only use this in a triggered job, then we're done with it
                  retention-days: 1
